### ISSUE TITLE
which preprocess_input used in extract_features.py

### ISSUE THREAD

**Issue by mushan09** [Gogul09/flower-recognition#19]
In extract_features.py, the code define seven preprocess_input:
`from keras.applications.vgg16 import VGG16, preprocess_input
from keras.applications.vgg19 import VGG19, preprocess_input
from keras.applications.xception import Xception, preprocess_input
from keras.applications.resnet50 import ResNet50, preprocess_input
from keras.applications.inception_resnet_v2 import InceptionResNetV2, preprocess_input
from keras.applications.mobilenet import MobileNet, preprocess_input
from keras.applications.inception_v3 import InceptionV3, preprocess_input`
So, when call `x = preprocess_input(x)` ,which preprocess_input was called?

**Comment by londere** [comment]
Hello DengBinbin according to the conf.json the model which is invoked is vgg19 you should change the conf.json if you need the other architecture of the listed.
