### ISSUE TITLE
Testing classifier using my own test data

### ISSUE THREAD

**Issue by SurionPL** [Gogul09/flower-recognition#3]
Hello! I have read your [post](https://gogul09.github.io/software/flower-recognition-deep-learning) but I still don't understand few things.

You created a folder named: **'dataset'** with two other folders: **'train'** and **'test'.** The _'organize_flowers_17.py'_ script  creates 17 folders in **output_path** (**\\flower-recognition\\dataset\\train**) and copies images into these labeled folders. In your **conf.json** file you defined **"train_path": "dataset/flowers_17"** but there is no folder **dataset/flowers_17** in your folder structure. Why do we need **'dataset/test'** folder?

And the most important question to me. How can I use my own test images? How algorithm will know which class the image belongs to? And then, do we need **"test_size"** setting in **conf.json** file?  I would be grateful for your reply. :)

**Comment by Gogul09** [comment]
Hi! I have updated the testing routine in `test.py`. You have to include some test images in `dataset/test`. The entire routine would be like this.
1. extract features
2. train classifier
3. test classifier

Hope this helps! Please let me know if there are some issues.
