### ISSUE TITLE
ValueError: No such layer: custom

### ISSUE THREAD

**Issue by sriramnagaraj** [Gogul09/flower-recognition#4]
Hello,
I get the following error when I run 'extract_features.py' 

Using TensorFlow backend.
[STATUS] start time - 2018-01-17 18:41
2018-01-17 18:41:56.202633: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "extract_features.py", line 65, in <module>
    model = Model(input=base_model.input, output=base_model.get_layer('custom').output)
  File "/Users/sriram/tensorflow/lib/python2.7/site-packages/keras/engine/topology.py", line 1887, in get_layer
    raise ValueError('No such layer: ' + name)
ValueError: No such layer: custom

After checking out on internet, I found out that we can create custom layers. Is there any simple alternative solution? I am trying this out on MacBook pro.

**Comment by sriramnagaraj** [comment]
Replace 'custom' with 'batch_normalization_1' in the extract_features.py

**Comment by Huixxi** [comment]
> Replace 'custom' with 'batch_normalization_1' in the extract_features.py

No such layer: batch_normalization_1

**Comment by neenu05** [comment]
> > Replace 'custom' with 'batch_normalization_1' in the extract_features.py
> 
> No such layer: batch_normalization_1

same error after running th code
how to solve it??...

**Comment by mehrezboulares** [comment]
ValueError: No such layer: batch_normalization_1 .   ?????? please how to resolve it ?
